# Generated by Django 4.1.7 on 2023-03-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_newspaper_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
